cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

stages:
  - install_deps
  - test

# 安装依赖
npm_install:
  stage: install_deps
  tags:
      - ttsy
  script:
    - npm install

# 运行测试用例
npm_test:
  stage: test
  tags:
      - ttsy
  script:
    - npm run test