stages:
  - install_deps
  - test

# 安装依赖
npm_install:
  stage: install_deps
  tags:
      - ttsy
  script:
    - npm install

# 运行测试用例
npm_test:
  stage: test
  tags:
      - lint
  script:
    - npm run test